# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  alias  = "noassume"
  region = "eu-central-1"
}

provider "aws" {
  profile = "deployment"
  assume_role {
    role_arn = "arn:aws:iam::002600688574:role/TerraformDeployment"
  }

  region = "eu-central-1"
}
